package com.interviewmanagementsystem.enums;

public enum CandidateStatus {
	OPEN,
	WAITING_FOR_INTERVIEW,
	CANCELLED_BY_INTERVIEW,
	PASSED_BY_INTERVIEW,
	FAILED_BY_INTERVIEW,
	WAITING_FOR_APPROVAL,
	APPROVED,
	REJECTED,
	WAITING_FOR_RESPONSE,
	ACCEPTED_OFFER,
	DECLINED_OFFER,
	CANCELLED_OFFER,
	BANNED
}
